<script lang="ts">
    import { onMount } from "svelte";
    import { typeText } from "../utils";
    import Block from "./Block.svelte";
    import ProjectCard from "./ProjectCard.svelte";
    import duskImage from "../assets/dusk-example.png";
    import itSpreadsImage from "../assets/it-spreads.jpg";
    import pumpkinSpiceImage from "../assets/pumpkin-spice.png";
    import hueNXImage from "../assets/hue-nx.jpg";
    import sweatErShopImage from "../assets/SweaterShop.png";
    import sparkForgeImage from "../assets/SparkForge.png";
    import whisperingEchosImage from "../assets/WhisperingEchos.png";

  import BottomBar from "./BottomBar.svelte";

    let titleText: HTMLHeadingElement;
    // let scrollDownText: HTMLParagraphElement;

    onMount(async () => {
        // type out the text
        typeText(titleText, 0, 1500);
        // typeText(scrollDownText, 1700, 1500);
    });

    const whisperingEchosDisc = "A game I wrote in my free time. It's written in a custom engine built on the Raylib game framework. ";
    const sparkForgeDisc = "An open source game engine I made that is intended to teach younger children programming using flowcharts and visual programming. It is then designed to slowly teach them how to program in a more traditional way by showing the code generated by their flowcharts.";

</script>



<div class="wrapper">
    <h1 class="title" bind:this={titleText}>
        Hi, I'm Julian.
    </h1>

    <div class="projects">
        <ProjectCard name="Whispering Echos" image={whisperingEchosImage} gridRow="1/3" gridColumn="2/4" description={whisperingEchosDisc}/>

        <ProjectCard name="SparkForge" image={sparkForgeImage} gridRow="4/5" gridColumn="2/5" description={sparkForgeDisc}/>
        
        <ProjectCard name="It Spreads" image={itSpreadsImage} gridRow="1/3" gridColumn="1/2"/>
        <ProjectCard name="Pumpkin Spice" image={pumpkinSpiceImage} gridRow="4/6" gridColumn="1/2"/>
        <ProjectCard name="Hue NX" image={hueNXImage} gridRow="3/4" gridColumn="3/4"/>
        <ProjectCard name="Sweat-er Shop" image={sweatErShopImage} gridRow="3/4" gridColumn="1/3"/>
        <ProjectCard name="DuSK Example Project" image={duskImage} gridRow="5/6" gridColumn="2/4"/>
    </div>

    <div class="spacer"/>

    <BottomBar/>
</div>



<style>

    .spacer{
        height: 10rem;
    }

    p{
        font-size: 2rem;
        font-weight: 400;
        color: var(--text-color);

        padding: 0;
        margin: 0;
    }

    .wrapper{
        display: grid;

        width: 100%;

        /* three columns */
        grid-template-columns: 1fr 1fr 1fr;

        /* two rows */
        grid-template-rows: 70dvh 30dvh;
    }

    .projects{
        grid-column: 1 / 4;
        grid-row: 2 / 4;

        height: 200dvh;

        padding: 10rem;

        display: grid;
        grid-template-columns: 1fr 1fr 1fr;
        grid-template-rows: 1fr 1fr 1fr 1fr 1fr;
    }

    .scroll-down{
        grid-column: 1 / 4;
        grid-row: 2 / 3;

        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;

        padding: 0;
        margin: 0;
    }

    .title{
        grid-column: 1 / 4;
        grid-row: 1 / 2;

        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;

        padding: 0;
        margin: 0;
    }

    h1{
        font-size: 7rem;
        font-weight: 700;
        color: var(--text-color);
    }

</style>
